# Generated by Django 4.1.5 on 2023-01-30 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_cnt',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PostCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.post')),
            ],
        ),
    ]
