# Generated by Django 4.1.4 on 2023-01-31 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eat", "0002_foodmenu_click_count_foodmenu_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="foodmenu", name="menu",),
        migrations.AddField(
            model_name="foodmenu",
            name="name",
            field=models.CharField(default=1, max_length=50, verbose_name="뭐먹지 메뉴이름"),
            preserve_default=False,
        ),
    ]
