# Generated by Django 4.1.4 on 2023-01-10 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='content',
            new_name='contents',
        ),
    ]
