# Generated by Django 4.1.4 on 2023-01-10 07:05

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('board', '0002_rename_content_board_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
