# Generated by Django 4.1.4 on 2023-01-23 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("where", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodcategory",
            name="category",
            field=models.CharField(max_length=50, verbose_name="음식카테고리"),
        ),
        migrations.AlterField(
            model_name="foodmenu",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="where.foodcategory",
                verbose_name="음식카테고리",
            ),
        ),
    ]
