# Generated by Django 4.1.5 on 2023-01-31 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_post_view_cnt_postcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='notice',
            field=models.BooleanField(default=False),
        ),
    ]
