# Generated by Django 4.1.5 on 2023-01-31 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_post_notice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCount',
        ),
    ]
