# Generated by Django 4.1.4 on 2023-01-31 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlayMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="뭐하지 메뉴이름")),
                (
                    "image",
                    models.ImageField(
                        default="playmenu/play_default.png",
                        upload_to="playmenu/",
                        verbose_name="뭐하지 이미지",
                    ),
                ),
                (
                    "click_count",
                    models.PositiveIntegerField(default=0, verbose_name="뭐하지 클릭수"),
                ),
            ],
        ),
    ]
