# Generated by Django 4.1.4 on 2023-01-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_content_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile/cat1.jpg', upload_to='profile', verbose_name='프로필 이미지'),
        ),
    ]
